apiVersion: v1
kind: Service
metadata:
    name: deployed
spec:
    type: NodePort
    ports:
      - port: 80
        nodePort: 30008
    selector:
        app: deployed
        type: front-end